version: '3'

services:
  pandora-next:
    image: pengzhile/pandora-next:latest
    container_name: PandoraNext
    networks:
      - pandora_network
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - ./data:/data
      - ./session/:/root/.cache/PandoraNext
    healthcheck:
      test: ["CMD-SHELL", "test -f /data/license.jwt"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pandora-proxy:
    image: pengzhile/pandora-next
    container_name: Pandoraproxy
    networks:
      - pandora_network
    restart: always
    depends_on:
      pandora-next:
        condition: service_healthy
    ports:
      - "8082:8082"
    volumes:
      - ./pandoraproxy/data:/data
      - ./data/license.jwt:/data/license.jwt
      - ./data/tokens.json:/data/tokens.json
      - ./session/:/root/.cache/PandoraNext

  tokensTool:
    image: yangclivia/tokenstool:latest
    container_name: tokensTool
    networks:
      - pandora_network
    restart: always
    user: root
    privileged: true
    ports:
      - "8081:8081"
    volumes:
      - /pandora/data:/pandora/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      - --deployWay=docker
      - --deployPosition=/pandora/data
      - --hotReload=true
      # --server.port=8182
      - --pandoara_Ip=default

networks:
  pandora_network:
    driver: bridge
